__package_name__ = "irods_rename"
__authors__ = "Boas van der Putten"
__email__ = "ids-bioinformatics@rivm.nl"
__license__ = "AGPLv3"
__version__ = "0.2.0"
__description__ = "Rename script for iRODS collections."
